import Hero from './components/home/products/BestProductsSection'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-montserat',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body
                className={`min-h-screen bg-primaryWhite ${montserrat.className}`}
            >
                <Navbar />

                <div>{children}</div>
            </body>
        </html>
    )
}
