import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-montserat',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html className={`${montserrat.className} `} lang="en">
            <body className={`overflow-x-hidden min-h-screen bg-primaryWhite`}>
                <Navbar />
                <div className="mx-8 md:mx-24 xl:mx-48">{children}</div>
            </body>
        </html>
    )
}
